### PR TITLE
Sponsers

### PR DESCRIPTION
**Pull request by reauctioned**
- Sponsers Section
- Sponsers logo
- Marquee animations
- Glassmorphic
- Lacking appropriate sponser logos (currently sponsered by wallet and a cup of tea)

### CODE REVIEW

**Comment by reauctioned** [comment]
Iffy respnsiveness atm, should be fixed soon

**Review by munannoo — APPROVED** [review]
okay

**Comment by reauctioned** [comment]
merge after fully functional

**Review by PhuyalGaurav — COMMENTED** [review]
Is it done yet?

**Comment by PhuyalGaurav** [comment]
image

wtf is this lol

**Comment by PhuyalGaurav** [comment]
image
and also why is not responsive anymore?

**Comment by reauctioned** [comment]
> image and also why is not responsive anymore?

No idea could not see that issue from my side.

**Comment by reauctioned** [comment]
> > image and also why is not responsive anymore?
> 
> No idea could not see that issue from my side.

Kay found it, will be fixed

**Comment by PhuyalGaurav** [comment]
i fixed it too.. are u working on it?

**Comment by reauctioned** [comment]
> i fixed it too.. are u working on it?

great, and no

**Comment by PhuyalGaurav** [comment]
maile bruh last ma k bigarey lol scroll nai ramrari hunna ta swiper js halna parla.
styling gar hai.

**Review by PhuyalGaurav — COMMENTED** [review]
Needs styling!

**Pull request merged**
